"""Some new change

Revision ID: 64c8a31fec50
Revises: 0ddfdbd400aa
Create Date: 2025-11-04 04:38:45.809252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c8a31fec50'
down_revision = '0ddfdbd400aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
